CREATE TABLE INGREDIENT (
  NAME VARCHAR(255),
  CONTAINS_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN
);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Eggs', false, true, false, true);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Bread', false, true, true, false);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Beef Patty', false, false, false, true);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Lettuce', false, true, true, true);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Yoghurt', true, true, false, true);

ALTER TABLE INGREDIENT 
ADD CONSTRAINT UNIQUE(NAME);

ALTER TABLE INGREDIENT
MODIFY CONTAINS_LACTOSE BOOLEAN NOT NULL;

ALTER TABLE INGREDIENT
MODIFY VEGETARIAN BOOLEAN NOT NULL;

ALTER TABLE INGREDIENT
MODIFY VEGAN BOOLEAN NOT NULL;

ALTER TABLE INGREDIENT
MODIFY GLUTEN_FREE BOOLEAN NOT NULL;